name: docker build and push

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - '.env'
      - '.github/workflows/build.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # read version from file
      - name: load version from file
        id: version
        run: echo "version=$(grep PLEROMA_VER .env | cut -d '=' -f2)" >> $GITHUB_OUTPUT

      # setup docker buildx
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      # bogin to GitHub Container Registry
      - name: log in to github registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # build and push
      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            PLEROMA_VER=${{ steps.version.outputs.version }}
